apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWkthSGU5SGp2a3N3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBNE16QXhNakk1TWpOYUZ3MHpOVEE0TWpneE1qTTBNak5hTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUURuTVVWTWpPaDZHR2FKWnhKckRBVHF6L3pRMEhiR2t5VHNpOGo5LzdKVXoyQzJPSG9YMitESFdTV2kKOVQ1T1BNUVU5YjdIdHkzaWNnN0k1TVpsMnpPc2d5SG9EbzJKL3IzY3hLaXpKM0xuOXlDamJodThZdjZZVG00QQpxZ0RvT0MzNjZDdnBxYTE0dDh6U2tHeXE2N3ZKSmU5OG5hdURFWXFJYmZHK0Q2RXdvcEtOVFAxUXJyelZ0QTlxCk8zZW81MmJhU0UyZ0s5eHAvb2ZqdFpQL1UzWHZNRE4xbW5zLzRNalNsRTBqWGczNGs3bXlueVZSMktmOUJqdkYKMjI2VHY3eFd2NkdNL0pzUmxCNVNPOXVIZFNOMTg2SjVWUFpqTS9PTUQraHlOTXlTbDBKZDVyTEE0NGtMOTNvUQp6QXJpclJ6OWRiYzBXVDZ6dUVjeXpWK0RSVDBCQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJRR1dpRmo5Zy9LUzMyckQxdGc1WEFKR0pibDJUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQkpncjE0MjRabQp3Z3lPTUJBckhQdUpLQ3lmN2ZkWFR2K3Y4MEpSNTQwNnJXU0hJUnVBY1JrZVgyMFg4NlUwam5HMDRCVVJSSUlLCnRLa1BIVGJ2bFZZczExOFdYeTRERS95NktWL2tmZk5EV3dETUVxclBvYllBaXdZTUxrd2FqeW90R3EveVl2M3UKY09Md0IrcHdzejJSNGNxVldxcm9Oc1RjRGNFR0NrOUZyNmtoTmZSMHBpMUc3Ukdmem91UWhrTDEva2J2ckpNVwpaT0JXU2ZObmRoNklGVnRGaDhaNEFEdDY1VVF5UzBjaitOWEYwZkhnRmJCSVNvOXFrTEhjS2M1YjkzMTg4R096CndYem9wYTdTRWlFV2FlRytUM0pRYnZvUlBHSnU5Ulc1UFFoa0syblEwMDBZV0hHR3EvbU85SkxFMU8yMGhJOGYKYy9tTTQzQ3VQbnUvCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
      server: https://1B6867D2476F456372410D19DB347A73.gr7.us-east-1.eks.amazonaws.com
    name: arn:aws:eks:us-east-1:116981767400:cluster/flight-central-cluster
contexts:
  - context:
      cluster: arn:aws:eks:us-east-1:116981767400:cluster/flight-central-cluster
      user: arn:aws:eks:us-east-1:116981767400:cluster/flight-central-cluster
    name: arn:aws:eks:us-east-1:116981767400:cluster/flight-central-cluster
current-context: arn:aws:eks:us-east-1:116981767400:cluster/flight-central-cluster
kind: Config
preferences: {}
users:
  - name: arn:aws:eks:us-east-1:116981767400:cluster/flight-central-cluster
    user:
      exec:
        apiVersion: client.authentication.k8s.io/v1beta1
        args:
          - --region
          - us-east-1
          - eks
          - get-token
          - --cluster-name
          - flight-central-cluster
          - --output
          - json
        command: aws