server.port=8090
spring.application.name=flight-booking

# AWS Secrets Manager Configuration
spring.cloud.config.server.aws-secretsmanager.region=us-east-1
spring.config.import=optional:aws-secretsmanager:flight-central/prod/credentials
aws.secretsmanager.region=us-east-1

# Connection Pool Settings
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-test-query=SELECT 1

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#cloud.aws.elasticache.cluster.name=flight-central-redis-cache-serverless


# Redis Configuration for ElastiCache
spring.redis.host=flight-central-redis-cache-serverless-xciyyl.serverless.use1.cache.amazonaws.com
spring.redis.port=6379
spring.data.redis.ssl.enabled=true
spring.redis.timeout=60000
spring.redis.lettuce.pool.max-active=8
spring.redis.lettuce.pool.max-wait=-1
spring.redis.lettuce.pool.max-idle=8
spring.redis.lettuce.pool.min-idle=0

# Cache Configuration
spring.cache.type=redis
spring.cache.redis.time-to-live=10m
spring.cache.redis.cache-null-values=false

# Database Connection with SSL
spring.datasource.url=${spring.datasource.url}
spring.datasource.username=${spring.datasource.username}
spring.datasource.password=${spring.datasource.password}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Logging
logging.level.org.postgresql=TRACE
logging.level.com.zaxxer.hikari=DEBUG
logging.level.org.hibernate=INFO